### ISSUE TITLE
plot_layout(guides = "collect") & theme(legend.position = 'bottom') printed a vertical legends

### ISSUE THREAD

**Issue by seheeopark** [thomasp85/patchwork#137]
I have two ggraphs to patch. 
``` r 
library(tidygraph)
library(ggraph) 

g1 <- gsi_wave1 %N>% 
  mutate(degree_sum = centrality_degree(mode = "all")) %>% 
  ggraph(layout = "kk") +
  geom_edge_link(aes(alpha = 0.5),
                 # Add arrow points 
                 arrow = arrow(length = unit(1, "mm")),
                 start_cap = circle(0.5, "mm"),
                 end_cap = circle(0.5, "mm")) +
  geom_node_point(aes(color = degree_sum,
                      alpha = 0.8)) + 
  scale_color_viridis(discrete = FALSE, option = "D") +
  theme_void() +
  ggtitle("GSI Network in wave 1 (2008-2010)")

g2 <- gsi_wave3 %N>% 
  mutate(degree_sum = centrality_degree(mode = "all")) %>% 
  ggraph(layout = "kk") +
  geom_edge_link(aes(alpha = 0.5),
                 # Add arrow points 
                 arrow = arrow(length = unit(1, "mm")),
                 start_cap = circle(0.5, "mm"),
                 end_cap = circle(0.5, "mm")) +
  geom_node_point(aes(color = degree_sum,
                      alpha = 0.8)) + 
  scale_color_viridis(discrete = FALSE, option = "D") +
  theme_void() +
  ggtitle("GSI Network in wave 3 (2015-2017)")

library(patchwork) 
g1 + g2 + plot_layout(guides = 'collect') & theme(legend.position = 'bottom')
```

The patched plot shows a collected legend in a vertical format. 
![plot_zoom](https://user-images.githubusercontent.com/54168331/70145151-c878c780-16e2-11ea-8c34-57263aa07ab1.png)

How can I get a collected legend in a horizontal format as in the individual graph?

**Comment by llrs** [comment]
I think that the color scale should be between the same values in order to be collected, this also applies to the alpha (and probably should use the same line type in both plots). 

BTW you didn't show the code used to compose these plots and I couldn't run the code you have because I don't know how to generate `gsi_wave1` nor `gsi_wave3`.

**Comment by seheeopark** [comment]
Hello Lluís 

Two graphs shared the same alpha for nodes and edges, and they are indeed collected. 
I understand that the degree_sum legends are not collected for having different scales. 

What I am curious about is why the collected 'bottom' legend takes a vertical format. 
If they are not collected, the labs of legends are in a horizontal format as this. 
``` r
library(patchwork) 
g1 + g2 
```
![plot_zoom2](https://user-images.githubusercontent.com/54168331/70207281-abd5a180-176d-11ea-8d63-a20f54292898.png)

Let me share the network data here (I had to delete other detailed node information, but the nodes and edges are the same): [gsi_network.zip](https://github.com/thomasp85/patchwork/files/3925279/gsi_network.zip)
Please note the changed data names:
* gsi_wave1_pb (~gsi_wave1~)
* gsi_wave3_pb (~gsi_wave3~) 

Thank you for your time and help.

**Comment by llrs** [comment]
Interestingly alpha and edge link gott collected but not the color. 

However, now that I look closer to the code if you have a fixed aesthetic you should use it outside the `aes` call (this will remove the guides for them):

Surprisingly I got another error when I change the order:
```
g1 + g2 & theme(legend.position = "bottom")  + plot_layout(guides = 'collect')
Error: Don't know how to add RHS to a theme object
```

Maybe the difference is that these plots are of class `ggraph` while ggplot2 plots are of class `gg`.  So it might need a different method for this class.

**Comment by jhrcook** [comment]
Hello Lluís,

The new error you are getting is from adding the `plot_layout()` function to the `theme()` function. Changing the ordering or adding parentheses will likely get the new error resolved.

 \- Josh

**Comment by dleopold** [comment]
Is there a solution to the initial question? Specifically, how to achieve two horizontal legends "collected" at the bottom, but next to each other instead of aligned vertically?.

**Comment by audrey-onfroy** [comment]
This issue is closed since 2020 but not resolved yet.
Maybe `legend.direction` in `theme()` answers the initial question :

## Quick answer : `legend.direction`

```
g1 + g2 + plot_layout(guides = 'collect') &
  theme(legend.position = 'bottom',
        legend.direction = 'horizontal')
```

##  Detailed answer (and collect color legend)

Moreover, to collect the color, setting the range the same allows to have only one legend for `degree_sum`. You should specify the `limits` in `scale_color_viridis`, for example :
`scale_color_viridis(discrete = FALSE, option = "D", limits = c(0,40))`.

I don't know how to extract in a simple way a range from a `tbl_graph` object but below is a solution. I used `lapply` to avoid writing two times the function. Then, `tidygraph::activate(nodes)` on each object to get the Node Data. Then, convert as data frame and extract only the column of interest and keep its range. `lapply` outputs a list containing the range for each object. Actually, this is [0, 32] and [0, 34]. Applying again `range` on it get the min of all lower bounds and max of all upper bounds : [0, 34].

```
gsi_wave1_pb <- gsi_wave1_pb %N>% 
  mutate(degree_sum = centrality_degree(mode = "all"))
gsi_wave3_pb <- gsi_wave3_pb %N>% 
  mutate(degree_sum = centrality_degree(mode = "all"))

degree_sum_range <- lapply(list(gsi_wave1_pb, gsi_wave3_pb),
                          FUN = function(gsi) {
                            gsi %>%
                              tidygraph::activate(nodes) %>%
                              data.frame() %>%
                              dplyr::pull(degree_sum) %>%
                              range()}) %>% range()
```

I don't change anything in the construction of your plots, but the `limits` parameter is set to `degree_sum_range` in `scale_color_viridis` function. Then, both plots will shared the same legend for color.

```
g1 <- ggraph(gsi_wave1_pb, layout = "kk") +
  geom_edge_link(aes(alpha = 0.5),
                 # Add arrow points 
                 arrow = arrow(length = unit(1, "mm")),
                 start_cap = circle(0.5, "mm"),
                 end_cap = circle(0.5, "mm")) +
  geom_node_point(aes(color = degree_sum,
                      alpha = 0.8)) + 
  scale_color_viridis(discrete = FALSE, option = "D", limits = degree_sum_range) +
  theme_void() +
  ggtitle("GSI Network in wave 1 (2008-2010)")

g2 <- ggraph(gsi_wave3_pb, layout = "kk") +
  geom_edge_link(aes(alpha = 0.5),
                 # Add arrow points 
                 arrow = arrow(length = unit(1, "mm")),
                 start_cap = circle(0.5, "mm"),
                 end_cap = circle(0.5, "mm")) +
  geom_node_point(aes(color = degree_sum,
                      alpha = 0.8)) + 
  scale_color_viridis(discrete = FALSE, option = "D", limits = degree_sum_range) +
  theme_void() +
  ggtitle("GSI Network in wave 3 (2015-2017)")
```

For the patchwork, do not forget the `legend.direction` in `theme()`.

```
g1 + g2 + plot_layout(guides = 'collect') &
  theme(legend.position = 'bottom',
        legend.direction = 'horizontal')
```
![horizontal](https://user-images.githubusercontent.com/71872404/155699444-2d0942c0-d4e5-4eb5-9396-02a9d1f0b321.png)

If you set `legend.direction` to vertical, the legend is displayed in three columns :

```
g1 + g2 + plot_layout(guides = 'collect') &
  theme(legend.position = 'bottom',
        legend.direction = 'vertical')
```
![vertical](https://user-images.githubusercontent.com/71872404/155699436-1bc5dae6-a274-4bdc-8c3d-49be81ca484e.png)

## Play also with `legend.box`

Note that in both figure, `legend.box` is by default `horizontal`. Set it `vertical` to have : 

```
g1 + g2 + plot_layout(guides = 'collect') &
  theme(legend.position = 'bottom',
        legend.direction = 'horizontal',
        legend.box = 'vertical')
```
![horizontal_vertical](https://user-images.githubusercontent.com/71872404/155701097-ee04675f-2413-4143-8316-d4e9aa05e806.png)

```
g1 + g2 + plot_layout(guides = 'collect') &
  theme(legend.position = 'bottom',
        legend.direction = 'vertical',
        legend.box = 'vertical')
```
![vertical_vertical](https://user-images.githubusercontent.com/71872404/155701109-eb27659b-bd58-411a-a214-e476128924a1.png)

Hope it helps !
