### ISSUE TITLE
Cannot patch grobs together

### ISSUE THREAD

**Issue by DanChaltiel** [thomasp85/patchwork#164]
Hi Thomas,

It is very easy to add a grob to a plot, as in your [vignette](https://patchwork.data-imaginist.com/articles/guides/assembly.html), but unfortunately, it seems impossible to directly add grobs together.

Here is an MRE, aiming to mimic your last example of the "Stacking and packing" example:

```
library(ggplot2)
p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  ggtitle('Plot 1')
p1 / (grid::textGrob('Some really important text') + grid::textGrob('Some also really important text'))
# Error: non-numeric argument to binary operator
```

The same happens with `|` instead of `+`, and I tried with `tableGrobs` with no more success.

Do you think it should be possible to add support for this?

**Comment by thomasp85** [comment]
It is unfortunately not possible due to limitations in the S3 dispatching system. I cannot control how the dispatching happens if it is not ggplot object that occurs first.

The way around that is to use `wrap_elements()`, though it does add some verbosity to the syntax. I did wish it would "just work"
