### ISSUE TITLE
Plots with unequal sizes despite right layout?

### ISSUE THREAD

**Issue by nitrato** [thomasp85/patchwork#165]
Hi Thomas,
Thanks for your work. I learned about patchwork on your great YouTube "Beyond ggplot2" tutorial and I love it.
I am currently running the following code with three plots in order to get a first row with the first two and a second row with a centered third plot. However, the output does not produce equal sized plots on the first row. If I keep the third one to the left, then everything seems OK. Any hints?
I am sending the dataset as well so that you can play with it yourself.
Thanks a lot.
[examData2.txt](https://github.com/thomasp85/patchwork/files/4482011/examData2.txt)

p1 <- ggplot(examData2, aes(x = Exam, y = Anxiety))+
  geom_point(size = 1, alpha = 0.5) +
  theme_minimal()

p2 <- ggplot(examData2, aes(x = Exam, y = Revise))+
  geom_point(size = 1, alpha = 0.5) +
  theme_minimal()

p3 <- ggplot(examData2, aes(x = Anxiety, y = Revise))+
  geom_point(size = 1, alpha = 0.5) +
  theme_minimal()

layout <- '1122
#33#'
png("exams.anxiety2.png", height = 10, width = 12, units = "cm", res = 300) 
p1 + p2 + p3 + plot_layout(design = layout)
dev.off()

**Comment by thomasp85** [comment]
The reason for this is indeed a bit non-obvious. The upper left plots span two plot regions, as do the upper right plot. All these 4 regions have the same size. But, because you've inserted the bottom plot, then the first and second plot regions get separated to make room for the axis and axis title of the bottom plot, meaning that the combined area gets larger.

The solution to this is to detach the top and bottom from each other, e.g. by:
```r
(p1 | p2) /
(plot_spacer() + p3 + plot_spacer() + plot_layout(widths = c(1,2,1)))
```

This is of course a bit more verbose, but I'd consider this a fringe case so I guess that is ok 🙂
