### ISSUE TITLE
plot_layout(axis_titles = "collect") does not work with fixed aspect ratio (and other coordinates beside coord_cartesian)

### ISSUE THREAD

**Issue by JFViola** [thomasp85/patchwork#403]
I fear that this is the same problem as in issue [https://github.com/thomasp85/patchwork/issues/366](url)

Collecting the axis titles of several plots does not work if coord_fixed, coord_sf or theme(aspect.ratio=1) is involved:

(ggplot2 version 3.5.1, patchwork version 1.3.0

```
#works
p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  coord_cartesian()+
  ggtitle('Plot 1')

p2 <- ggplot(mtcars*-1) + 
  geom_point(aes(mpg, disp)) + 
  coord_cartesian()+
  ggtitle('Plot 2')

p1 + p2 +
  plot_layout(axis_titles  = 'collect')
```

```
#does not work
p1 <- ggplot(mtcars) + 
  geom_point(aes(mpg, disp)) + 
  coord_fixed()+
#alternatively
#coord_sf()+
#theme(aspect.ratio=1)+
  ggtitle('Plot 1')

p2 <- ggplot(mtcars*-1) + 
  geom_point(aes(mpg, disp)) + 
  coord_fixed()+
#alternatively
#coord_sf()+
#theme(aspect.ratio=1)+
  ggtitle('Plot 2')

p1 + p2 +
  plot_layout(axis_titles  = 'collect')
```

**Comment by thomasp85** [comment]
Yes, there is no way to ensure that plots with fixed aspects are actually occupying the same vertical or horizontal space when resizing the plot so collecting the axes doesn't make sense in general. For sf plots it is due to the fact that they do not use the new guide setup for their axes. If/when that changes in ggplot2 it should work out of the box

**Comment by JFViola** [comment]
Alright thank you. I think it was a misunderstanding on my end, I wanted to collect labels not titles.
