### ISSUE TITLE
Feature request: shared axes

### ISSUE THREAD

**Issue by prosoitos** [thomasp85/patchwork#81]
Thank you so much for this package. I truly love it.

The main reason I still use gridExtra most of the time is because I often don't want to have each graph with its own axes. But I really would prefer to use patchwork if I could.

Are you planning on implementing this? Are you still planning on developing this package further?

Thank you!

**Comment by thomasp85** [comment]
This package will be developed further, as well as be released on CRAN. I do have other priorities at the moment but will get back to it by the end of the year hopefully.

I am currently ambivalent about implementing automatic hiding of axes as it can easily get messy with nested layouts etc. For now, you can always hide the axis you don't want to see in each plot individually be setting e.g. `p + theme(axis.x.text = element_blank(), ...)`

What I do plan to implement is to automatically collect all legends to one side, removing duplicates in the process (sort of what you are asking, but with legends instead of axes)

**Comment by prosoitos** [comment]
Thank you for the update!

And good idea about setting some of the axes with `element_blank()`.
