### ISSUE TITLE
add text box long caption in bottom row?

### ISSUE THREAD

**Issue by higgi13425** [thomasp85/patchwork#99]
Hi Thomas!
It is quite common in my field to display a multipanel figure, with each panel tagged with a letter, then have a long descriptive caption of each panel in sequence in a single page-wide text blob below the multipanel figure (see example below). Is there a straightforward way to create this layout with patchwork? possibly with patchwork and RMarkdown?
 
Thanks!

![Capture](https://user-images.githubusercontent.com/13680616/58764955-a63b9c80-853b-11e9-993c-43c4876e0e2a.PNG)

**Comment by thomasp85** [comment]
I would think this is usually the job of the typesetting software, be it LaTeX, word or some flavour of markdown. I don’t think vanilla RMarkdown supports figure captions, but pretty sure this is possible in bookdown or pagedown. If you want to achieve this you could simply stack your plots on top of a text grob, but grid has pretty bad support for mixing fonts and weight which is why I would go with the first approach

**Comment by thomasp85** [comment]
Once grid text is mature, such a grob could be added to the patchwork as a textbox. AFAIK text wrapping is still a problem, though

**Comment by higgi13425** [comment]
for text wrapping,
would 
stringr::str_wrap
or
base::strwrap 
or 
pathview::wordwrap 
or
stringi::stri_wrap

help?
    On Tuesday, November 19, 2019, 07:09:40 AM EST, Thomas Lin Pedersen <notifications@github.com> wrote:  
 
 
Once grid text is mature, such a grob could be added to the patchwork as a textbox. AFAIK text wrapping is still a problem, though

**Comment by thomasp85** [comment]
not really... all of these wrap strings based on number of glyphs, not based on absolute length of string. To be clear, the calculations are already possible, but the mechanics of grid makes it difficult to implement properly
